---
- name: Create docker-compose directory
  ansible.builtin.file:
    path: "{{ apps_dir }}/docker-compose/"
    state: directory

- name: Copy project dir
  copy:
    src: "./docker-compose/{{ service_dir }}"
    dest: "{{ apps_dir }}/docker-compose/"

- name: Check if .env.j2 file exists
  stat:
    path: "./docker-compose/{{ service_dir }}/compose/.env.j2"
  register: env_file_stat
  delegate_to: localhost
  become: false

- name: Fill in template env files
  template:
    src: "./docker-compose/{{ service_dir }}/compose/.env.j2"
    dest: "{{ apps_dir }}/docker-compose/{{ service_dir }}/compose/.env"
  when: env_file_stat.stat.exists

- block:
    - name: Build and run services
      community.docker.docker_compose_v2:
        project_src: "{{ apps_dir }}/docker-compose/{{ service_dir }}/compose"
        files: "compose.yml"
        state: present

  rescue:
    - name: Logging
      debug:
        msg: "Error when docker compose up"
  always:
    - name: Cleanup temporary files
      file:
        path: "{{ apps_dir }}/docker-compose/{{ service_dir }}/compose/.env"
        state: absent
    - name: Cleanup temporary files
      file:
        path: "{{ apps_dir }}/docker-compose/{{ service_dir }}/compose/.env.j2"
        state: absent

